// setup.js
export const GET_BG_COLOUR = "GET_BG_COLOUR";
// export const FETCH_TIMEZONES_SUCCESS = "FETCH_TIMEZONES_SUCCESS"
// export const FETCH_COMMUNICATION_PREFERENCES = "FETCH_COMMUNICATION_PREFERENCES"
