name: MarkdownLint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            markdown: '**/*.md'

      - uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20b273450ec8265 # v19.1.0
        if: steps.filter.outputs.markdown == 'true'
        with:
          config: '.markdownlint-cli2.jsonc'
          globs: '**/*.md'
        continue-on-error: true
