name: MarkdownLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@v37
        id: changed-files
        with:
          files: '**/*.md'
          separator: ","

      - uses: DavidAnson/markdownlint-cli2-action@v11
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          config: '.markdownlint-cli2.jsonc'
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
        continue-on-error: true
